version: '3'
services:
        web1:
                build: ./web1
                ports:
                 - '80:80'

        web2:
                build: ./web2
                ports:
                 - '443:433'

        cache:
                build: ./cache
                ports:
                 - '8080:8080'

        balancer:
                build: ./balancer
                ports:
                 - '8000:8000'
